### ISSUE TITLE
miniconda installer on windows: to not register python by default

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#20]
as discovered in https://github.com/datalad/datalad-installer/pull/17#issuecomment-773558226 - miniconda installer for windows lacks option to not set default python to be the miniconda's .  We should file an issue or better submit PR against miniconda installer to add such possibility.

**Comment by jwodder** [comment]
@yarikoptic I cannot reproduce this.  Before & after running `python datalad_install.py miniconda --path ~/foo` (and after closing & reopening git-bash; post-reboot not checked), in both git-bash and the command prompt, `python -c "import sys; print(sys.executable)"` gives me `C:\Users\DataLad\AppData\Local\Programs\Python\Python39\python.exe`, which is the python.org installation rather than any Miniconda installation.

I would expect the Miniconda installer to only set the default Python if it's not already set, and since Python is needed to run datalad-installer, I normally wouldn't expect this to be an issue.  How did you install Python on your Windows VM before running datalad-installer?

**Comment by yarikoptic** [comment]
did you reboot? but may be it is indeed if only no system wide python was already available... I will try to try from scratch later on

**Comment by jwodder** [comment]
@yarikoptic `sys.executable` is unchanged even after rebooting.

**Comment by yarikoptic** [comment]
gotcha -- need to reproduce... may be was some kind of a fluke...

**Comment by yarikoptic** [comment]
ok, let's consider being a fluke.  I will reopen if I run into it again
